dist: bionic
language: cpp

addons:
  apt:
    packages:
      - g++
      - libboost-program-options-dev
      - libgtest-dev
      - cmake

before_install:
  - cd /usr/src/googletest/googletest
  - mkdir build
  - cd build
  - cmake ..
  - make install
  - cd ..
  - rm -rf build

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - ./webpptest
