dist: bionic
language: cpp

addons:
  apt:
    packages:
      - g++
      - libboost-program-options-dev
      - libgtest-dev
      - cmake

before_install:
  - sudo mkdir /usr/src/googletest/googletest/build
  - cd /usr/src/googletest/googletest/build
  - sudo cmake ..
  - sudo make install
  - sudo rm -rf /usr/src/googletest/googletest/build
  - cd -

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - ./webpptest
