dist: bionic
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - libboost-dev
      - googletest
      - cmake

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build
  - ./webpptest
