dist: bionic
language: cpp

addons:
  apt:
    packages:
      - g++
      - libboost-dev
      - libboost-program-options-dev
      - libgtest-dev
      - googletest
      - cmake

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .
  - ./webpptest
